name: Go deploy testing

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd /root/port-page
            git pull origin main
            go build .

            ./port-page