name: Go deploy testing

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            APP_PATH=/home/${{secrets.USERNAME}}/port-page/port-page
            GO_PATH=/usr/local/go/bin/go
            cd /home/${{secrets.USERNAME}}/port-page
            git pull origin main
            ${GO_PATH} build .
            sudo nohup ${APP_PATH} &
            exit 0